repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
    -   id: black
        exclude: ^.*migrations.*
-   repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
    -   id: flake8
        args: [--max-line-length=88]
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v3.14.0
    hooks:
    -   id: reorder-python-imports
        exclude: ^.*/migrations/
