""" "test running migrations"

Revision ID: 02e3b278697b
Revises: f23637f5efaf
Create Date: 2025-01-27 18:05:47.422562

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "02e3b278697b"
down_revision = "f23637f5efaf"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
