""" "test running migrations"

Revision ID: 08b04889468e
Revises: 76d59a375947
Create Date: 2025-01-30 14:43:24.504322

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "08b04889468e"
down_revision = "76d59a375947"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
