""" "test running migrations"

Revision ID: 0adde07e4fca
Revises: 48a055e6d794
Create Date: 2025-01-27 12:51:30.773028

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "0adde07e4fca"
down_revision = "48a055e6d794"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
