""" "test running migrations"

Revision ID: 0b217ba0d1d3
Revises: 3c74f1799f76
Create Date: 2025-01-28 18:31:16.487910

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "0b217ba0d1d3"
down_revision = "3c74f1799f76"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
