""" "test running migrations"

Revision ID: 10acb5b8d552
Revises: 3f71d2f13378
Create Date: 2025-01-27 17:58:23.678978

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "10acb5b8d552"
down_revision = "3f71d2f13378"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
