""""test running migrations"

Revision ID: 161ed11c8766
Revises: 156ec4484516
Create Date: 2025-01-27 12:47:32.373647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '161ed11c8766'
down_revision = '156ec4484516'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
