""""test running migrations"

Revision ID: 173cb3f939f3
Revises: 5fbab19890e6
Create Date: 2025-01-30 14:35:57.071837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '173cb3f939f3'
down_revision = '5fbab19890e6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
