""""test running migrations"

Revision ID: 1f53da3ab749
Revises: c98430973fa2
Create Date: 2025-01-28 18:55:53.936142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f53da3ab749'
down_revision = 'c98430973fa2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
