""""test running migrations"

Revision ID: 20e89c206c27
Revises: d0c438d28553
Create Date: 2025-01-27 17:52:21.446825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20e89c206c27'
down_revision = 'd0c438d28553'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
