""" "test running migrations"

Revision ID: 26870d77dfbe
Revises: 4ffa8ea54cdc
Create Date: 2025-01-29 22:14:46.963590

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "26870d77dfbe"
down_revision = "4ffa8ea54cdc"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
