""" "test running migrations"

Revision ID: 2a158606fa2b
Revises: a5c47c4ef367
Create Date: 2025-01-27 17:43:40.750643

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "2a158606fa2b"
down_revision = "a5c47c4ef367"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
