""""test running migrations"

Revision ID: 2d7b0dacb82b
Revises: 818fca6d7b34
Create Date: 2025-01-27 12:28:31.783851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d7b0dacb82b'
down_revision = '818fca6d7b34'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
