""" "test running migrations"

Revision ID: 2ed4aef726bf
Revises: f2060e2e895f
Create Date: 2025-01-27 16:18:01.537314

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "2ed4aef726bf"
down_revision = "f2060e2e895f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
