""" "test running migrations"

Revision ID: 31f695609e8f
Revises: 53fee64f866f
Create Date: 2025-01-28 19:42:59.563228

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "31f695609e8f"
down_revision = "53fee64f866f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
