""" "test running migrations"

Revision ID: 3c74f1799f76
Revises: f070bbc5fe94
Create Date: 2025-01-28 18:29:01.242608

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "3c74f1799f76"
down_revision = "f070bbc5fe94"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
