""""test running migrations"

Revision ID: 3d6d6240f414
Revises: e70bcbca02c2
Create Date: 2025-01-28 19:11:18.077256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d6d6240f414'
down_revision = 'e70bcbca02c2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
