""""test running migrations"

Revision ID: 3f71d2f13378
Revises: 61c7aa977972
Create Date: 2025-01-27 17:57:00.695354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f71d2f13378'
down_revision = '61c7aa977972'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
