""""test running migrations"

Revision ID: 40e56d9196a1
Revises: 8c4a74264a76
Create Date: 2025-01-27 16:22:37.665325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40e56d9196a1'
down_revision = '8c4a74264a76'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
