""""test running migrations"

Revision ID: 485d9be6a90f
Revises: 20e89c206c27
Create Date: 2025-01-27 17:54:57.406393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '485d9be6a90f'
down_revision = '20e89c206c27'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
