""" "test running migrations"

Revision ID: 48a055e6d794
Revises: 161ed11c8766
Create Date: 2025-01-27 12:48:06.571331

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "48a055e6d794"
down_revision = "161ed11c8766"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
