""" "test running migrations"

Revision ID: 4f2bfe5e8a04
Revises: 69b5bfff6d5a
Create Date: 2025-01-28 19:21:39.678045

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "4f2bfe5e8a04"
down_revision = "69b5bfff6d5a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
