""""test running migrations"

Revision ID: 53fee64f866f
Revises: e83409afd522
Create Date: 2025-01-28 19:35:27.717233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53fee64f866f'
down_revision = 'e83409afd522'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
