""""test running migrations"

Revision ID: 5405409e41a8
Revises: 344fdc4240d3
Create Date: 2025-01-27 16:12:36.479279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5405409e41a8'
down_revision = '344fdc4240d3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
