""" "test running migrations"

Revision ID: 599a323e2255
Revises: 10acb5b8d552
Create Date: 2025-01-27 18:00:40.704531

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "599a323e2255"
down_revision = "10acb5b8d552"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
