""""test running migrations"

Revision ID: 5e12c61ddc4d
Revises: b8c2df54483a
Create Date: 2025-01-27 16:31:23.717881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e12c61ddc4d'
down_revision = 'b8c2df54483a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
