""" "test running migrations"

Revision ID: 5fbab19890e6
Revises: 7010eff86bda
Create Date: 2025-01-29 22:56:16.640619

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "5fbab19890e6"
down_revision = "7010eff86bda"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
