""" "test running migrations"

Revision ID: 61c7aa977972
Revises: 485d9be6a90f
Create Date: 2025-01-27 17:56:00.189027

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "61c7aa977972"
down_revision = "485d9be6a90f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
