""" "test running migrations"

Revision ID: 636c32ca2ae8
Revises: 1f53da3ab749
Create Date: 2025-01-28 18:56:35.334436

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "636c32ca2ae8"
down_revision = "1f53da3ab749"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
