""""test running migrations"

Revision ID: 67b28ff4194c
Revises: bdff6fa31633
Create Date: 2025-01-30 15:41:32.896539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67b28ff4194c'
down_revision = 'bdff6fa31633'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
