""" "test running migrations"

Revision ID: 6a221b450a50
Revises: 2a158606fa2b
Create Date: 2025-01-27 17:49:45.465134

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "6a221b450a50"
down_revision = "2a158606fa2b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
