""" "test running migrations"

Revision ID: 6b0e3b208301
Revises: 02e3b278697b
Create Date: 2025-01-27 18:06:11.310195

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "6b0e3b208301"
down_revision = "02e3b278697b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
