""" "test running migrations"

Revision ID: 7010eff86bda
Revises: e5096550600d
Create Date: 2025-01-29 22:55:37.269434

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "7010eff86bda"
down_revision = "e5096550600d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
