""" "test running migrations"

Revision ID: 76d59a375947
Revises: 241294107563
Create Date: 2025-01-30 14:38:53.894553

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "76d59a375947"
down_revision = "241294107563"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
