""""test running migrations"

Revision ID: 7d64c25b04f2
Revises: 87c9cf587b5e
Create Date: 2025-01-27 16:34:25.882420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d64c25b04f2'
down_revision = '87c9cf587b5e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
