""" "test running migrations"

Revision ID: 89d3f331aa98
Revises: 43f0ef1a01b2
Create Date: 2025-01-27 12:34:18.882711

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "89d3f331aa98"
down_revision = "43f0ef1a01b2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
