""""test running migrations"

Revision ID: 8c4a74264a76
Revises: f68d742fb687
Create Date: 2025-01-27 16:22:08.616918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c4a74264a76'
down_revision = 'f68d742fb687'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
