""" "test running migrations"

Revision ID: 9201f6df2793
Revises: 599a323e2255
Create Date: 2025-01-27 18:02:53.113340

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "9201f6df2793"
down_revision = "599a323e2255"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
