""" "test running migrations"

Revision ID: 93f0a65acf52
Revises: 5e12c61ddc4d
Create Date: 2025-01-27 16:31:34.800857

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "93f0a65acf52"
down_revision = "5e12c61ddc4d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
