""" "test running migrations"

Revision ID: 94f3301c62a1
Revises: 4f2bfe5e8a04
Create Date: 2025-01-28 19:24:36.008603

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "94f3301c62a1"
down_revision = "4f2bfe5e8a04"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
