""""test running migrations"

Revision ID: 9e8231a28bac
Revises: eabe7e3217c8
Create Date: 2025-01-28 18:53:07.477479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e8231a28bac'
down_revision = 'eabe7e3217c8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
