""" "test running migrations"

Revision ID: 9f5568a0663d
Revises: c5028f7f4de1
Create Date: 2025-01-27 17:35:52.341808

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "9f5568a0663d"
down_revision = "c5028f7f4de1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
