""" "test running migrations"

Revision ID: aca00460cdcc
Revises: f73d9c13717d
Create Date: 2025-01-29 22:15:31.470999

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "aca00460cdcc"
down_revision = "f73d9c13717d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
