""" "test running migrations"

Revision ID: b31ffe919713
Revises: d0ff5a80cf4c
Create Date: 2025-01-27 16:46:42.384283

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "b31ffe919713"
down_revision = "d0ff5a80cf4c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
