""" "test running migrations"

Revision ID: b888d5bcd5f0
Revises: 636c32ca2ae8
Create Date: 2025-01-28 18:57:28.399845

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "b888d5bcd5f0"
down_revision = "636c32ca2ae8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
