""" "test running migrations"

Revision ID: b8c2df54483a
Revises: 12fa459413f3
Create Date: 2025-01-27 16:27:10.648754

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "b8c2df54483a"
down_revision = "12fa459413f3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
