""" "test running migrations"

Revision ID: bc02ce11d025
Revises: f365ea24ebab
Create Date: 2025-01-27 12:57:49.294374

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "bc02ce11d025"
down_revision = "f365ea24ebab"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
