""" "test running migrations"

Revision ID: bdff6fa31633
Revises: 08b04889468e
Create Date: 2025-01-30 14:44:21.446732

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "bdff6fa31633"
down_revision = "08b04889468e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
