""" "test running migrations"

Revision ID: c1660817682e
Revises: e44c18879240
Create Date: 2025-01-27 16:35:01.800255

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "c1660817682e"
down_revision = "e44c18879240"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
