""" "test running migrations"

Revision ID: c3898da99434
Revises: 9f5568a0663d
Create Date: 2025-01-27 17:37:55.743900

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "c3898da99434"
down_revision = "9f5568a0663d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
