""" "test running migrations"

Revision ID: c4abf5e087a4
Revises: b31ffe919713
Create Date: 2025-01-27 16:47:10.525055

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "c4abf5e087a4"
down_revision = "b31ffe919713"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
