""""test running migrations"

Revision ID: c5b19af8533d
Revises: ae9591b7a9b6
Create Date: 2025-01-27 18:25:14.402233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5b19af8533d'
down_revision = 'ae9591b7a9b6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
