""" "test running migrations"

Revision ID: c910541daa93
Revises: fc3ac778d8a7
Create Date: 2025-01-27 16:19:19.366077

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "c910541daa93"
down_revision = "fc3ac778d8a7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
