""""test running migrations"

Revision ID: c98430973fa2
Revises: f92d30305a50
Create Date: 2025-01-28 18:55:13.437260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c98430973fa2'
down_revision = 'f92d30305a50'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
