""""test running migrations"

Revision ID: d0ff5a80cf4c
Revises: 20100a91bfda
Create Date: 2025-01-27 16:46:27.060540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0ff5a80cf4c'
down_revision = '20100a91bfda'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
