""""test running migrations"

Revision ID: d44bb2bbd9e2
Revises: 43feed7997e7
Create Date: 2025-01-28 18:24:14.047183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd44bb2bbd9e2'
down_revision = '43feed7997e7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
