""" "test running migrations"

Revision ID: d5543bab874b
Revises: dea0d3baf6ab
Create Date: 2025-01-28 19:15:31.165452

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "d5543bab874b"
down_revision = "dea0d3baf6ab"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
