""""test running migrations"

Revision ID: dab06e2af77c
Revises: 9f2d5868cdf6
Create Date: 2025-01-29 22:39:30.880310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dab06e2af77c'
down_revision = '9f2d5868cdf6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
