""" "test running migrations"

Revision ID: e5096550600d
Revises: fb53052c25ad
Create Date: 2025-01-29 22:50:03.630788

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "e5096550600d"
down_revision = "fb53052c25ad"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
