""""test running migrations"

Revision ID: e70bcbca02c2
Revises: b888d5bcd5f0
Create Date: 2025-01-28 18:58:19.325624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e70bcbca02c2'
down_revision = 'b888d5bcd5f0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
