""" "test running migrations"

Revision ID: e7ce4728e62b
Revises: 25b12c79df4c
Create Date: 2025-01-27 12:56:24.605782

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "e7ce4728e62b"
down_revision = "25b12c79df4c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
