""" "test running migrations"

Revision ID: e83409afd522
Revises: fcc7d7d29f96
Create Date: 2025-01-28 19:28:26.154540

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "e83409afd522"
down_revision = "fcc7d7d29f96"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
