""" "test running migrations"

Revision ID: e9c6a1ea3f44
Revises: ef9551177cb4
Create Date: 2025-01-27 12:43:25.469436

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "e9c6a1ea3f44"
down_revision = "ef9551177cb4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
