""" "test running migrations"

Revision ID: ea9765fd36ef
Revises: 7b1205aa20fd
Create Date: 2025-01-28 18:06:35.085805

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "ea9765fd36ef"
down_revision = "7b1205aa20fd"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
