""""test running migrations"

Revision ID: ef9551177cb4
Revises: b3b8bf69c6b7
Create Date: 2025-01-27 12:42:06.081340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef9551177cb4'
down_revision = 'b3b8bf69c6b7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
