""""test running migrations"

Revision ID: f070bbc5fe94
Revises: d44bb2bbd9e2
Create Date: 2025-01-28 18:26:27.008437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f070bbc5fe94'
down_revision = 'd44bb2bbd9e2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
