""" "test running migrations"

Revision ID: f23637f5efaf
Revises: 9201f6df2793
Create Date: 2025-01-27 18:05:27.951105

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "f23637f5efaf"
down_revision = "9201f6df2793"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
