""""test running migrations"

Revision ID: f365ea24ebab
Revises: e7ce4728e62b
Create Date: 2025-01-27 12:56:49.759640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f365ea24ebab'
down_revision = 'e7ce4728e62b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
