""" "test running migrations"

Revision ID: f68d742fb687
Revises: b9c3e08e592a
Create Date: 2025-01-27 16:21:56.807246

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "f68d742fb687"
down_revision = "b9c3e08e592a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
