""""test running migrations"

Revision ID: f92d30305a50
Revises: 9e8231a28bac
Create Date: 2025-01-28 18:54:26.767685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f92d30305a50'
down_revision = '9e8231a28bac'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
