""" "test running migrations"

Revision ID: fcc7d7d29f96
Revises: 96fa3ff4aea4
Create Date: 2025-01-28 19:27:59.274300

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "fcc7d7d29f96"
down_revision = "96fa3ff4aea4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
